CREATE TABLE HOUFINCSUPLLIST (
    YEAR CHAR(4) NOT NULL,              --년
    MONTH CHAR(2) NOT NULL,             --월
    INSTITUTE_CODE VARCHAR(2) NOT NULL, --기관코드
    INSTITUTE_AMT INT(15) DEFAULT 0,    --기관명
    PRIMARY KEY (YEAR,MONTH,INSTITUTE_CODE)
)